import { StyleSheet } from 'react-native';

export const metaCardStyles = StyleSheet.create({
    cardContainer: {
        backgroundColor: '#0B0B0C',
        borderRadius: 14,
        padding: 14,
        flexDirection: 'column',
        position: 'relative',
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#1F2933',
        gap: 10,
    },
    cardContainerNoTopContent: {
        gap: 14,
    },
    cardHeader: {
        marginTop: -14,
        marginLeft: -14,
        flexDirection: 'row',
        alignItems: 'center',
    },
    topLeftContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        borderTopLeftRadius: 14,
        borderBottomRightRadius: 14,
        padding: 0,
        marginRight: 50,
    },
    topLeftContainerNoAction: {
        marginRight: 0,
    },
    dateTimePill: {
        backgroundColor: '#111827', // colors.white.light[300] equivalent but dark
        color: '#F9FAFB',
        borderTopLeftRadius: 14,
        borderBottomRightRadius: 14,
        paddingHorizontal: 12,
        paddingVertical: 2,
        fontSize: 13,
        fontWeight: '700',
        marginRight: 4,
        borderRightWidth: 1,
        borderBottomWidth: 1,
        borderColor: '#1F2933',
    },
    topLeftContent: {
        backgroundColor: '#111827',
        color: '#F9FAFB',
        borderTopLeftRadius: 14,
        borderBottomRightRadius: 14,
        paddingHorizontal: 12,
        paddingVertical: 2,
        fontSize: 13,
        fontWeight: '700',
        borderRightWidth: 1,
        borderBottomWidth: 1,
        borderColor: '#1F2933',
        maxWidth: '100%',
        marginRight: 4,
        position: 'relative',
        zIndex: 2,
    },
    statusBadgeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        position: 'relative',
        zIndex: 1,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        paddingTop: 2,
        paddingBottom: 3,
        paddingHorizontal: 20,
        fontSize: 13,
        fontWeight: '700',
        borderBottomRightRadius: 14,
        marginLeft: -12,
        overflow: 'hidden',
    },
    actionStrip: {
        position: 'absolute',
        top: 0,
        right: 0,
        bottom: 0,
        width: 50,
        backgroundColor: '#2563EB',
        alignItems: 'flex-start',
        justifyContent: 'flex-end',
        paddingTop: 6,
        paddingRight: 4,
    },
    actionButtonsContainer: {
        position: 'absolute',
        top: 0,
        right: -14,
        flexDirection: 'row',
        justifyContent: 'center',
        paddingHorizontal: 9,
        paddingVertical: 0,
        backgroundColor: '#111827',
        borderBottomLeftRadius: 14,
        borderBottomWidth: 1,
        borderLeftWidth: 1,
        borderColor: '#1F2933',
        gap: 8,
    },
    actionButton: {
        height: 35,
        minWidth: 35,
        paddingHorizontal: 10,
        backgroundColor: '#111827',
        alignItems: 'center',
        justifyContent: 'center',
        borderBottomLeftRadius: 14,
    },
    contentContainer: {
        paddingRight: 0,
        flexDirection: 'row',
    },
    contentContainerExpandable: {
        paddingRight: 28,
    },
    imageContainer: {
        flexShrink: 0,
        alignSelf: 'flex-start',
        width: 54,
        height: 54,
        borderRadius: 8,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#1F2933',
        marginRight: 10,
    },
    image: {
        width: 54,
        height: 54,
    },
    expandIconWrapper: {
        position: 'absolute',
        bottom: 10,
        right: 10,
        backgroundColor: '#FFFFFF',
        width: 24,
        height: 24,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
});
