#!/usr/bin/env node

const { execSync } = require('child_process');
const fs = require('fs');

const args = process.argv.slice(2);
const HARD = args.includes('--hard');

const run = (cmd) => {
    console.log(`\n🔸 ${cmd}`);
    execSync(cmd, { stdio: 'inherit' });
};

const rm = (target) => {
    if (fs.existsSync(target)) {
        console.log(`🔹 Removing ${target}`);
        execSync(`rm -rf "${target}"`);
    }
};

console.log('==========================================');
console.log('        🧹 React Native Cleaner (npm)');
console.log('==========================================');

// 1) JS deps (only on --hard)
if (HARD) rm('node_modules');

// 2) JS + bundler caches
rm('.expo');
rm('.expo-shared');
rm('.expo-internal');
rm('.parcel-cache');
rm('.bundler');

// 3) Native folders (these are regenerated by prebuild anyway)
rm('android');
rm('ios');

// 4) Reinstall JS deps (always)
run('npm install');

// 5) Re-run Expo prebuild
run('npx expo prebuild --clean');

// 6) Install iOS Pods
if (fs.existsSync('ios')) {
    run('cd ios && pod install --repo-update');
}

// 7) Optional iOS Xcode DerivedData cleanup (only on --hard)
if (HARD) {
    run('rm -rf ~/Library/Developer/Xcode/DerivedData/*');
}

console.log('\n==========================================');
console.log('      ✅ Cleaning Complete (npm)');
console.log('You can now run:');
console.log('   npm run ios');
console.log('   npm run android');
console.log('==========================================\n');
